### ISSUE TITLE
Field 'issue' in comment.tk

### ISSUE THREAD

**Issue by crguezl** [plaguera/commen.tk#23]
What is the meaning/need to choose an issue in the comment.tk form when following the decision path:

Organization -> Repo -> issue

It is not clear to me the need to set an initial issue

**Comment by plaguera** [comment]
#24 Specifying the issue number is now optional, it is possible to use the page's hostname, pathname or title to look for the issue automatically. It is being tested currently and will be merged to master branch and put in production shortly.
